blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/wesrom/wesrom/discussions/new?category=q-a
    about: Please ask your question in the discussion forum of this repository.
  - name: Roadmap
    url: https://github.com/wesrom/wesrom/projects/2
    about: Please review our public roadmap repository before suggesting a feature.
